import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';
import { pathToFileURL } from 'node:url';

import { buildAndStageFrontends } from '../scripts/build-frontends.mjs';
import { createCombinedHost } from '../apps/web-host/dist/combined-host.js';

function apiFactory({ fastify }) {
  fastify.all('/trpc/*', (_request, reply) => {
    reply.code(404).send({ error: 'reserved API route' });
  });
  return Promise.resolve({
    init: () => fastify.ready(),
    close: () => fastify.close(),
    enableShutdownHooks() {},
    listen: (port, host) => fastify.listen({ port, host }),
  });
}

test(
  'Astro 7 middleware build loads through the combined Fastify host',
  { timeout: 120_000 },
  async (t) => {
    const repoDir = process.cwd();
    const stagingDir = await mkdtemp(
      path.join(repoDir, 'apps', 'web-host', '.astro7-staging-'),
    );
    t.after(() => rm(stagingDir, { recursive: true, force: true }));

    await buildAndStageFrontends({ repoDir, stagingDir });

    const entryUrl = pathToFileURL(
      path.join(stagingDir, 'web', 'server', 'entry.mjs'),
    );
    const runtime = await import(entryUrl.href);
    assert.equal(typeof runtime.handler, 'function');

    const host = await createCombinedHost({
      sitesDir: stagingDir,
      primaryFrontend: 'web',
      apiFactory,
    });
    await host.app.listen(0, '127.0.0.1');
    t.after(() => host.app.close());

    const address = host.fastify.server.address();
    assert.equal(typeof address, 'object');
    const origin = `http://127.0.0.1:${address.port}`;

    const primary = await fetch(`${origin}/`);
    assert.equal(primary.status, 200);
    const html = await primary.text();
    assert.match(
      html,
      /<div class="nav-wordmark">mono<span class="slash">\/<\/span>repo<\/div>/,
    );
    assert.match(
      html,
      /<h1>One codebase,<br>every<em>moving part<\/em><br>connected<\/h1>/,
    );

    const stylesheet = html.match(/href="(\/_astro\/[^"?]+\.css)"/);
    assert.ok(stylesheet, 'SSR output references a built client stylesheet');
    const asset = await fetch(`${origin}${stylesheet[1]}`);
    assert.equal(asset.status, 200);
    assert.match(asset.headers.get('cache-control') ?? '', /immutable/);
    assert.match(await asset.text(), /\.home-shell/);

    const secondary = await fetch(`${origin}/secondary-web/`);
    assert.equal(secondary.status, 200);
    const secondaryHtml = await secondary.text();
    assert.match(
      secondaryHtml,
      /<h1 id="page-title"[^>]*>Secondary Astro App<\/h1>/,
    );
    assert.match(
      secondaryHtml,
      /This page is generated by a second Astro workspace and served from the same Node process as the primary web app\./,
    );
  },
);
